src/Entity/EventCalendar.php
<?php

namespace App\Entity;

use App\Repository\EventCalendarRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventCalendarRepository::class)
 */
class EventCalendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $begin_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_at = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_available = 1 ;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBeginAt(): ?\DateTimeInterface
    {
        return $this->begin_at;
    }

    public function setBeginAt(?\DateTimeInterface $begin_at): self
    {
        $this->begin_at = $begin_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(?\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): self
    {
        $this->is_available = $is_available;

        return $this;
    }
}

src/Form/EventCalendarType.php
<?php

namespace App\Form;

use App\Entity\EventCalendar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventCalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('begin_at')
            ->add('end_at')
            ->add('title')
            ->add('is_available')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => EventCalendar::class,
        ]);
    }
}

src/Controller/EventCalendarController.php
<?php

namespace App\Controller;

use App\Entity\EventCalendar;
use App\Form\EventCalendarType;
use App\Repository\EventCalendarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/calendar")
 */
class EventCalendarController extends AbstractController
{
    /**
     * @Route("/", name="calendar_vue", methods={"GET"})
     */
    public function vue(EventCalendarRepository $eventCalendarRepository): Response
    {
        return $this->render('event_calendar/vue.html.twig', [
            //'event_calendars' => $eventCalendarRepository->findAll(),
        ]);
    }

    /**
     * @Route("/index", name="eventcalendar_index", methods={"GET"})
     */
    public function index(EventCalendarRepository $eventCalendarRepository): Response
    {
        return $this->render('event_calendar/index.html.twig', [
            'event_calendars' => $eventCalendarRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="eventcalendar_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $eventCalendar = new EventCalendar();
        $form = $this->createForm(EventCalendarType::class, $eventCalendar, [
            //'action' => $this->generateUrl('eventcalendar_new')
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($eventCalendar);
            $entityManager->flush();

            return $this->redirectToRoute('eventcalendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event_calendar/new.html.twig', [
            'event_calendar' => $eventCalendar,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/get_availables", name="eventcalendar_getavailables", methods={"POST"})
     */
    public function getAvailables(Request $request): Response
    {
        $eventCalendar = new EventCalendar();
        $form = $this->createForm(EventCalendarType::class, $eventCalendar, [
            //'action' => $this->generateUrl('eventcalendar_new')
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($eventCalendar);
            $entityManager->flush();

            return $this->redirectToRoute('eventcalendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event_calendar/new.html.twig', [
            'event_calendar' => $eventCalendar,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="eventcalendar_show", methods={"GET"})
     */
    public function show(EventCalendar $eventCalendar): Response
    {
        return $this->render('event_calendar/show.html.twig', [
            'event_calendar' => $eventCalendar,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="eventcalendar_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, EventCalendar $eventCalendar): Response
    {
        $form = $this->createForm(EventCalendarType::class, $eventCalendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('eventcalendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event_calendar/edit.html.twig', [
            'event_calendar' => $eventCalendar,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="eventcalendar_delete", methods={"POST"})
     */
    public function delete(Request $request, EventCalendar $eventCalendar): Response
    {
        if ($this->isCsrfTokenValid('delete'.$eventCalendar->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($eventCalendar);
            $entityManager->flush();
        }

        return $this->redirectToRoute('eventcalendar_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event_calendar/_delete_form.html.twig
<form method="post" action="{{ path('eventcalendar_delete', {'id': event_calendar.id}) }}" onsubmit="return confirm('Supprimer définitivement cet event ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event_calendar.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/event_calendar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/event_calendar/edit.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Événement{% endblock title %}

    {% block main %}

        <h2>Modifier l'événement</h2>

        {{ include('event_calendar/_form.html.twig', {'button_label': 'Modifier'}) }}

        <a href="{{ path('eventcalendar_index') }}">Retour à la liste</a>
    
        {{ include('event_calendar/_delete_form.html.twig') }}
        
    
    {% endblock main %}

templates/event_calendar/index.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Calendrier : liste des événements{% endblock title %}

    {% block main %}

        <h2>Liste des événements</h2>

        <a href="{{ path('eventcalendar_new') }}">Ajouter un événement</a>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th>Libellé</th>
                    <th>Affichage calendrier</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for event_calendar in event_calendars %}
                <tr>
                    <td>{{ event_calendar.id }}</td>
                    <td>{{ event_calendar.beginAt ? event_calendar.beginAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ event_calendar.endAt ? event_calendar.endAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ event_calendar.title }}</td>
                    <td>{{ event_calendar.isAvailable ? 'Oui' : 'Non' }}</td>
                    <td>
                        <a href="{{ path('eventcalendar_show', {'id': event_calendar.id}) }}">Voir</a>
                        <a href="{{ path('eventcalendar_edit', {'id': event_calendar.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucun événement trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endblock main %}

templates/event_calendar/new.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Calendrier : Ajouter un événement{% endblock title %}

    {% block main %}

        <h2>Ajouter un nouvel événement au calendrier</h2>

        {{ include('event_calendar/_form.html.twig') }}

        <a href="{{ path('calendar_vue') }}">Retour au calendrier</a>
        
    
    {% endblock main %}

templates/event_calendar/show.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Événement{% endblock title %}

    {% block main %}

        <h2>Détails d'un événement</h2>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ event_calendar.id }}</td>
                </tr>
                <tr>
                    <th>Début</th>
                    <td>{{ event_calendar.beginAt ? event_calendar.beginAt|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Fin</th>
                    <td>{{ event_calendar.endAt ? event_calendar.endAt|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Libellé</th>
                    <td>{{ event_calendar.title }}</td>
                </tr>
                <tr>
                    <th>Affichage calendrier</th>
                    <td>{{ event_calendar.isAvailable ? 'Yes' : 'No' }}</td>
                </tr>
            </tbody>
        </table>
    
        <a href="{{ path('calendar_vue') }}">Retour au calendrier</a>
    
        <a href="{{ path('eventcalendar_edit', {'id': event_calendar.id}) }}">Modifier</a>
    
        {{ include('event_calendar/_delete_form.html.twig') }}
        
    
    {% endblock main %}

templates/event_calendar/vue.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Calendrier{% endblock title %}

    {% block stylesheets %}{{ parent() }}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css">
    {% endblock stylesheets %}

    {% block main %}

        <h2>Calendrier</h2>

        <a href="{{ path('eventcalendar_new') }}">Ajouter un événement</a>

        <div id="calendar-holder"></div>
    
    
    {% endblock main %}

    {% block javascripts %}{{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>
{% endblock javascripts %}