src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use App\Repository\TomeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    const FORMAT_MANGA = 'Manga' ;
    const FORMAT_NOVEL = 'Roman' ;
    const FORMAT_BOOK = 'Ouvrage' ;

    const STATUS_PUBLIHING_ANNOUNCED = 'Annoncé' ;
    const STATUS_PUBLIHING_INPROGRESS = 'En cours' ;
    const STATUS_PUBLIHING_ABANDONED = 'Abandonné' ;
    const STATUS_PUBLIHING_FINISHED = 'Terminé' ;

    const STATUS_COLLECTION_GAIN = 'À acquérir' ;
    const STATUS_COLLECTION_INPROGRESS = 'En cours' ;
    const STATUS_COLLECTION_ABANDONED = 'Abandonné' ;
    const STATUS_COLLECTION_FULL = 'Complet' ;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $id_artist;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $publishing_house;

    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    private $is_serie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $is_serie_nb_tomes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status_publication;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status_collection;

    /**
     * @ORM\Column(type="boolean", options={"default": 1})
     */
    private $is_available;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $format;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genre;

    /**
     * @ORM\OneToMany(targetEntity=Tome::class, mappedBy="id_book")
     */
    private $tomes;

    public function __construct()
    {
        $this->tomes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIdArtist(): ?int
    {
        return $this->id_artist;
    }

    public function setIdArtist(?int $id_artist): self
    {
        $this->id_artist = $id_artist;

        return $this;
    }

    public function getPublishingHouse(): ?string
    {
        return $this->publishing_house;
    }

    public function setPublishingHouse(?string $publishing_house): self
    {
        $this->publishing_house = $publishing_house;

        return $this;
    }


    public function getIsSerie(): ?bool
    {
        return $this->is_serie;
    }

    public function setIsSerie(bool $is_serie): self
    {
        $this->is_serie = $is_serie;

        return $this;
    }

    public function getIsSerieNbTomes(): ?int
    {
        return $this->is_serie_nb_tomes;
    }

    public function setIsSerieNbTomes(?int $is_serie_nb_tomes): self
    {
        $this->is_serie_nb_tomes = $is_serie_nb_tomes;

        return $this;
    }

    public function getStatusPublication(): ?string
    {
        return $this->status_publication;
    }

    public function setStatusPublication(?string $status_publication): self
    {
        $this->status_publication = $status_publication;

        return $this;
    }

    public function getStatusCollection(): ?string
    {
        return $this->status_collection;
    }

    public function setStatusCollection(?string $status_collection): self
    {
        $this->status_collection = $status_collection;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): self
    {
        $this->is_available = $is_available;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): self
    {
        $this->format = $format;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection|Tome[]
     */
    public function getTomes(): Collection
    {
        return $this->tomes;
    }

    public function addTome(Tome $tome): self
    {
        if (!$this->tomes->contains($tome)) {
            $this->tomes[] = $tome;
            $tome->setIdBook($this);
        }

        return $this;
    }

    public function removeTome(Tome $tome): self
    {
        if ($this->tomes->removeElement($tome)) {
            // set the owning side to null (unless already changed)
            if ($tome->getIdBook() === $this) {
                $tome->setIdBook(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        return $this->id;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('id_artist')
            ->add('is_serie')
            ->add('is_serie_nb_tomes')
            ->add('publishing_house')
            ->add('status_publication')
            ->add('status_collection')
            ->add('is_available')
            ->add('format')
            ->add('genre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use App\Repository\TomeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/book")
 */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="book_index", methods={"GET"})
     */
    public function index(BookRepository $bookRepository): Response
    {
        return $this->render('book/index.html.twig', [
            'books_oneshot' => $bookRepository->findAvailableBooksOneshot(),
            'books_serie' => $bookRepository->findAvailableBooksSerie()
        ]);
    }

    /**
     * @Route("/new", name="book_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/new.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="book_show", methods={"GET"})
     */
    public function show(Book $book, TomeRepository $tomeRepository): Response
    {
        $nb = $tomeRepository->getNbTomesFromBook($book->getId());

        return $this->render('book/show.html.twig', [
            'book'      => $book,
            'nb_tomes'  => $nb
        ]);
    }

    /**
     * @Route("/{id}/edit", name="book_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Book $book): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/edit.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="book_delete", methods={"POST"})
     */
    public function delete(Request $request, Book $book): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('book_delete', {'id': book.id}) }}" onsubmit="return confirm('Supprimer définitivement ce livre ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Modifier un livre{% endblock title %}

    {% block main %}

        <h2>Modifier le livre</h2>

        {{ include('book/_form.html.twig', {'button_label': 'Modifier'}) }}

        <a href="{{ path('book_show', {'id': book.id}) }}">Retour à la fiche</a>
    
        {{ include('book/_delete_form.html.twig') }}
        
    
    {% endblock main %}

templates/book/index.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Calendrier : liste des livres{% endblock title %}

    {% block main %}
        <section>
            <div class="mt-4 mb-4">
                <h2 class="d-inline">Liste des livres oneshots</h2>
                <a href="{{ path('book_new') }}">Ajouter un livre</a>
            </div>
            

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Titre</th>
                        <th>Auteur·rice</th>
                        <th>Maison d'édition (statut)</th>
                        <th>Format</th>
                        <th>Genre</th>
                        <th>Disponible</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for book in books_oneshot %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <td><a href="{{ path('book_show', {'id': book.id}) }}">{{ book.title }}</a></td>
                        <td>{{ book.idArtist }}</td>
                        <td>{{ book.publishingHouse }} {% if book.statusPublication %}({{ book.statusPublication }}){% endif %}</td>
                        <td>{{ book.format }}</td>
                        <td>{{ book.genre }}</td>
                        <td>{{ book.isAvailable ? 'Oui' : 'Non' }}</td>
                        <td><a href="{{ path('book_edit', {'id': book.id}) }}">Modifier</a></td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="10">Aucun résultat trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>

        <hr class="mt-4 mb-4"/>

        <section>
            <div class="mt-4 mb-4">
                <h2 class="d-inline">Liste des livres à plusieurs tomes</h2>
                <a href="{{ path('book_new') }}">Ajouter un livre</a>
            </div>
            

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Titre</th>
                        <th>Auteur·rice</th>
                        <th>Série</th>
                        <th>Progression</th>
                        <th>Nombre de tomes</th>
                        <th>Maison d'édition (statut)</th>
                        <th>Format</th>
                        <th>Genre</th>
                        <th>Disponible</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for book in books_serie %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <td><a href="{{ path('book_show', {'id': book.id}) }}">{{ book.title }}</a></td>
                        <td>{{ book.idArtist }}</td>
                        <td>{{ book.isSerie ? 'Oui' : 'Non' }}</td>
                        <td>{{ book.statusCollection }}</td>
                        <td>{{ book.isSerieNbTomes }}</td>
                        <td>{{ book.publishingHouse }} {% if book.isSerie %}({{ book.statusPublication }}){% endif %}</td>
                        <td>{{ book.format }}</td>
                        <td>{{ book.genre }}</td>
                        <td>{{ book.isAvailable ? 'Oui' : 'Non' }}</td>
                        <td><a href="{{ path('book_edit', {'id': book.id}) }}">Modifier</a></td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="10">Aucun résultat trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>


    {% endblock main %}

templates/book/new.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Ajouter un livre{% endblock title %}

    {% block main %}

        <h2>Ajouter un livre</h2>

        {{ include('book/_form.html.twig') }}

        <a href="{{ path('book_index') }}">Retour à la liste</a>
        
    {% endblock main %}

templates/book/show.html.twig
{% extends 'root.twig' %}

    {% block title %}{{ parent() }} - Livre{% endblock title %}

    {% block main %}
    <section class="container mt-4">
        <div class="mb-4">
            <h2 class="d-inline">{{ book.title }} (id {{ book.id }})</h2>
            <a href="{{ path('book_edit', {'id': book.id}) }}">Modifier</a>
        </div>

        <div>Auteur·rice : {{ book.idArtist }}</div>
        <div>Maison d'édition (statut) : {{ book.publishingHouse }} ({{ book.statusPublication }})</div>
        <div>Disponible : {{ book.isAvailable ? 'Oui' : 'Non' }}</div>
        <div>Format : {{ book.format }}</div>
        <div>Genre : {{ book.genre }}</div>

        <div class="d-flex flex-wrap justify-content-between mt-4">
            <a href="{{ path('book_index') }}">Retour à la liste</a>
            {{ include('book/_delete_form.html.twig') }}
        </div>

        <!----------------------------------------------->
        {% if book.isSerie %}
        <section class="mt-4">
            <div class="mb-4">
                <h3 class="d-inline">Tomes possédés ({{ nb_tomes }}/{{ book.isSerieNbTomes }}, {{ book.statusCollection}})</h3>
                <a href="{{ path('tome_new') }}">Ajouter un tome</a>
            </div>
            
            {% for aTome in book.tomes %}
                <a href="{{ path('tome_show', {'id': aTome.id}) }}"><img class="maxi-vignette" src="/img/cover/books/{{aTome.cover}}" alt="{{ aTome.title }}" /></a>
            {% endfor %}
        </section>
        {% endif %}

    </section>
    {% endblock %}