src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SongRepository::class)
 */
class Song
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title_vo;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $bpm;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $explanations;

    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    private $is_veto;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTitleVo(): ?string
    {
        return $this->title_vo;
    }

    public function setTitleVo(?string $title_vo): self
    {
        $this->title_vo = $title_vo;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getBpm(): ?int
    {
        return $this->bpm;
    }

    public function setBpm(?int $bpm): self
    {
        $this->bpm = $bpm;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getExplanations(): ?string
    {
        return $this->explanations;
    }

    public function setExplanations(?string $explanations): self
    {
        $this->explanations = $explanations;

        return $this;
    }

    public function getIsVeto(): ?bool
    {
        return $this->is_veto;
    }

    public function setIsVeto(bool $is_veto): self
    {
        $this->is_veto = $is_veto;

        return $this;
    }
}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Song;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('title_vo')
            ->add('year')
            ->add('bpm')
            ->add('note')
            ->add('explanations')
            ->add('is_veto')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Song::class,
        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Song;
use App\Form\SongType;
use App\Repository\SongRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/song")
 */
class SongController extends AbstractController
{
    /**
     * @Route("/", name="song_index", methods={"GET"})
     */
    public function index(SongRepository $songRepository): Response
    {
        return $this->render('song/index.html.twig', [
            'songs' => $songRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="song_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $song = new Song();
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($song);
            $entityManager->flush();

            return $this->redirectToRoute('song_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('song/new.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="song_show", methods={"GET"})
     */
    public function show(Song $song): Response
    {
        return $this->render('song/show.html.twig', [
            'song' => $song,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="song_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Song $song): Response
    {
        $form = $this->createForm(SongType::class, $song);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('song_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('song/edit.html.twig', [
            'song' => $song,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="song_delete", methods={"POST"})
     */
    public function delete(Request $request, Song $song): Response
    {
        if ($this->isCsrfTokenValid('delete'.$song->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($song);
            $entityManager->flush();
        }

        return $this->redirectToRoute('song_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/song/_delete_form.html.twig
<form method="post" action="{{ path('song_delete', {'id': song.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ song.id) }}">
    <button class="btn">Delete</button>
</form>

templates/song/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/song/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Song{% endblock %}

{% block body %}
    <h1>Edit Song</h1>

    {{ include('song/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('song_index') }}">back to list</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}

templates/song/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song index{% endblock %}

{% block body %}
    <h1>Song index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Title_vo</th>
                <th>Year</th>
                <th>Bpm</th>
                <th>Note</th>
                <th>Explanations</th>
                <th>Is_veto</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for song in songs %}
            <tr>
                <td>{{ song.id }}</td>
                <td>{{ song.title }}</td>
                <td>{{ song.titleVo }}</td>
                <td>{{ song.year }}</td>
                <td>{{ song.bpm }}</td>
                <td>{{ song.note }}</td>
                <td>{{ song.explanations }}</td>
                <td>{{ song.isVeto ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('song_show', {'id': song.id}) }}">show</a>
                    <a href="{{ path('song_edit', {'id': song.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('song_new') }}">Create new</a>
{% endblock %}

templates/song/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Song{% endblock %}

{% block body %}
    <h1>Create new Song</h1>

    {{ include('song/_form.html.twig') }}

    <a href="{{ path('song_index') }}">back to list</a>
{% endblock %}

templates/song/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song{% endblock %}

{% block body %}
    <h1>Song</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ song.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ song.title }}</td>
            </tr>
            <tr>
                <th>Title_vo</th>
                <td>{{ song.titleVo }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ song.year }}</td>
            </tr>
            <tr>
                <th>Bpm</th>
                <td>{{ song.bpm }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ song.note }}</td>
            </tr>
            <tr>
                <th>Explanations</th>
                <td>{{ song.explanations }}</td>
            </tr>
            <tr>
                <th>Is_veto</th>
                <td>{{ song.isVeto ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('song_index') }}">back to list</a>

    <a href="{{ path('song_edit', {'id': song.id}) }}">edit</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}